{% set name = "pbgcpp" %}
{% set version = "0.2.7" %}
{% set sha256 = "0b5e83d72aa7e8e32feebfe1425ebf65f3da1abc07b1eb3ab93764b38d72cd87" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  #url: https://github.com/PacificBiosciences/unanimity/releases/download/v{{ version }}/ccs
  url: https://github.com/PacificBiosciences/pypeFLOW/releases/download/0.2.7/falcon_kit-1.3.0.tar.gz
  sha256: {{ sha256 }}

about:
  home: https://github.com/PacificBiosciences/pbbioconda
  license: BSD-3-Clause-Clear
  summary: pbgcpp - GenomicConsensus in C++

extra:
  recipe-maintainers:
    - armintoepfer
    - pb-dseifert
    - pb-cdunn
    - mhsieh

build:
  number: 0
  skip: True # [osx]

test:
  commands:
    - gcpp -h
