package:
  name: pymzml
  version: "2.2.1"

source:
  url: https://files.pythonhosted.org/packages/81/7e/e9c6c86b58d4c11cfc7a5d97f093f846344bf74e4edaa7ab6d68e2751810/pymzml-2.2.1.tar.gz
  sha256: 586d0e1b4a3fa5630da45f11ff57db6b2b97e08c58f8ca2887fa70eee132f7b5

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >3
    - pip
  run:
    - python >3
    - plotly

test:
  imports:
    - pymzml

about:
  home: http://pymzml.github.com
  license: GNU General Public License (GPL)
  summary: 'high-throughput mzML parsing'
  license_family: LGPL

extra:
  identifiers:
    - biotools:pymzml
