{% set name = "biobb_chemistry" %}
{% set version = "1.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8c10c9a0046df6a539c7f01516315f1e80cc9100a4db2cf6fb13f30a29147354

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - biobb_common ==0.1.4
    - pip
    - python
  run:
    - biobb_common ==0.1.4
    - python

test:
  imports:
    - biobb_chemistry
    - biobb_chemistry.test

about:
  home: https://github.com/bioexcel/biobb_chemistry
  license: Apache Software
  license_family: APACHE
  license_file: 
  summary: Biobb_md is the Biobb module collection to perform molecular dynamics simulations.
  doc_url: 
  dev_url: 
