package:
  name: cancerit-allelecount
  version: '4.0.2'
source:
  url: https://github.com/cancerit/alleleCount/archive/v4.0.2.tar.gz
  sha256: f11be42c3adde1796c98bb5b1443f43d60e0c62c66daadfa965c87d391d33449
build:
  number: 0
  skip: True # [osx]
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - zlib
    - wget
  run:
    - zlib
test:
  commands:
    - 'alleleCounter -h'
about:
  home: https://github.com/cancerit/alleleCount
  license: GPLv3
  summary: Support code for NGS copy number algorithms
