{% set version = "3.7.1" %}

package:
  name: weblogo
  version: {{ version }}

build:
  noarch: python
  number: 0

source:
  url: https://github.com/WebLogo/weblogo/archive/3.7.1.tar.gz
  sha256: 84e75fc3d72def07701014f5c1e07d9953a8d2b37ecd46a6d85cd994a6ec771e

requirements:
  host:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy
    - ghostscript

test:
  imports:
    - corebio
    - corebio.seq_io
    - corebio.seq_io._nexus
    - corebio.utils
    - weblogolib
  commands:
    - weblogo -h
    - transformseq -h

about:
  home: https://github.com/WebLogo/weblogo
  license: MIT
  summary: 'WebLogo3 : Sequence Logos Redrawn'
  license_family: MIT

extra:
  identifiers:
    - biotools:weblogo
    - doi:10.1101/gr.849004
