{% set version = "2.1.1" %}

package:
  name: mash
  version: {{ version }}

source:
  url: https://github.com/marbl/Mash/archive/v{{ version }}.tar.gz
  sha256: 77a949e81e21b88acb0df8bfacb418e63ad763597f3430cd0f653d0a167842aa

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - autoconf
    - automake
  host:
    - zlib
    - capnproto
    - gsl
    - openblas
  run:
    - zlib
    - capnproto
    - gsl
    - openblas
test:
  commands:
    - mash -h

about:
  home: https://github.com/marbl/Mash
  license: "https://raw.githubusercontent.com/marbl/Mash/master/LICENSE.txt"
  summary: "Fast sequence distance estimator that uses MinHash"
